### ISSUE TITLE
Calendar widget Behavior

### ISSUE THREAD

**Issue by listyque** [Southpaw-TACTIC/TACTIC#1496] opened 2020-06-23 13:58 UTC
**Describe the bug**
Calendar widget looks very different depending on browsers. For example how it looks with Edge:
![image](https://user-images.githubusercontent.com/13370598/85412660-81fd9400-b572-11ea-9942-62dc41cad920.png)
And how it looks on Opera/Chrome:
![image](https://user-images.githubusercontent.com/13370598/85412731-96419100-b572-11ea-8fd5-f9b42c3438c2.png)
It looks really bad on Chrome and not so oblivious due too it's different look.

**To Reproduce**
1. Click on create new task
2. Click on caledar

**Expected behavior**
Consistent or similar look on different browsers.

**Comment by remkonoteboom** [comment] 2020-06-23 14:35
This is a tricky one.  I had recently moved the calendar widget to use the HTML5 standard which uses the browser specific one because it guarantees that it will work as a proper input.

<input type="calendar"/>

This means that the built-in input element is completely determined by the browser.  This is the effect of using built-in browser widgets.

Alternatively, the TACTIC builtin-calendar did produce a consistent output but the element was in the DOM and was subject to DOM rules (built-in inputs are not).

**Comment by listyque** [comment] 2020-06-23 16:36
The old TACTIC 4.5 calendar works just fine. Can it be reused in 4.8?
![image](https://user-images.githubusercontent.com/13370598/85451302-67dbaa00-b5a2-11ea-93fd-b77bb707ec1e.png)

**Comment by remkonoteboom** [comment] 2020-06-24 14:00
Yes, except that it was subject to being hidden when in a popup, which was the issue described here:

https://github.com/Southpaw-TACTIC/TACTIC/issues/1490

The problem is that the TACTIC calendar is actually in the DOM and subject to DOM rules, including being partially hidden.  The built-in widget is never hidden because it is build in the browser outside the DOM.  Now with a bit of work, this can be fixed by putting the calendar in absolute space and positioning properly but it would take a bit of work.

That being said, I have not deleted the old TACTIC calendar and can be accessed using

<display class="CalendarInputWdg">
  <display_mode>tactic</display_mode>
</display>

Or if you want the default to be for the whole project, you can add a project setting with key "calendar_display_mode" set "tactic".

Or there is now a global setting for all projects in the config file

<global_setting>
      <calendar_display_mode>tactic</calendar_display_mode>
</global_setting>

**Closed as completed** 2020-06-24 14:05 UTC
